//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Badge.java
//  @ Date : 20/10/2016
//  @ Author : 
//
//




public class Badge
{
    private String titulo;
    private String imagem;
}
