//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cliente.java
//  @ Date : 20/10/2016
//  @ Author : 
//
//




public class Cliente
{
    private String username;
    private String senha;
    private String nome;
    private String telefone;
    private Datetime usuarioDesde;
    private String celular;
    private String email;
}
