//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Denuncia.java
//  @ Date : 20/10/2016
//  @ Author : 
//
//




public class Denuncia
{
}
