//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Jogo.java
//  @ Date : 20/10/2016
//  @ Author : 
//
//




public class Jogo
{
    private float valorNovo;
    private String produtora;
    private String titulo;
    private String subtitulo;
    private String capa;
}
