//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Midia.java
//  @ Date : 20/10/2016
//  @ Author : 
//
//




public class Midia
{
    private double statusMidia;
    private String tipo;
}
