//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Plataforma.java
//  @ Date : 20/10/2016
//  @ Author : 
//
//




public class Plataforma
{
    private String descricao;
    private String tipo;
}
