//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Proposta.java
//  @ Date : 20/10/2016
//  @ Author : 
//
//




public class Proposta
{
    private Datetime dataHoraCriacao;
    private String status;
}
