-- MySQL Script generated by MySQL Workbench
-- 10/20/16 21:22:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema trocagame
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `trocagame` ;

-- -----------------------------------------------------
-- Schema trocagame
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trocagame` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
SHOW WARNINGS;
USE `trocagame` ;

-- -----------------------------------------------------
-- Table `trocagame`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trocagame`.`cliente` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `trocagame`.`cliente` (
  `username` VARCHAR(20) NOT NULL,
  `senha` VARCHAR(128) NULL,
  `nome` VARCHAR(45) NULL,
  `sobrenome` VARCHAR(45) NULL,
  `celular` VARCHAR(15) NULL,
  `telefone` VARCHAR(15) NULL,
  `usuarioDesde` DATETIME NULL,
  `email` VARCHAR(80) NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `trocagame`.`jogo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trocagame`.`jogo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `trocagame`.`jogo` (
  `id` BIGINT UNSIGNED NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `subtitulo` VARCHAR(45) NULL,
  `produtora` VARCHAR(45) NULL,
  `capa` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `trocagame`.`midia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trocagame`.`midia` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `trocagame`.`midia` (
  `id` INT UNSIGNED NOT NULL,
  `status` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `jogo_id` BIGINT UNSIGNED NOT NULL,
  `cliente_username` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`, `jogo_id`, `cliente_username`),
  CONSTRAINT `fk_midia_jogo1`
    FOREIGN KEY (`jogo_id`)
    REFERENCES `trocagame`.`jogo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_midia_cliente1`
    FOREIGN KEY (`cliente_username`)
    REFERENCES `trocagame`.`cliente` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;
CREATE INDEX `fk_midia_jogo1_idx` ON `trocagame`.`midia` (`jogo_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_midia_cliente1_idx` ON `trocagame`.`midia` (`cliente_username` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `trocagame`.`badge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trocagame`.`badge` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `trocagame`.`badge` (
  `id` BIGINT NOT NULL,
  `imagem` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `trocagame`.`cliente_has_badge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trocagame`.`cliente_has_badge` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `trocagame`.`cliente_has_badge` (
  `cliente_username` VARCHAR(20) NOT NULL,
  `badge_id` BIGINT NOT NULL,
  PRIMARY KEY (`cliente_username`, `badge_id`),
  CONSTRAINT `fk_cliente_has_badge_cliente1`
    FOREIGN KEY (`cliente_username`)
    REFERENCES `trocagame`.`cliente` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_has_badge_badge1`
    FOREIGN KEY (`badge_id`)
    REFERENCES `trocagame`.`badge` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;
CREATE INDEX `fk_cliente_has_badge_badge1_idx` ON `trocagame`.`cliente_has_badge` (`badge_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_cliente_has_badge_cliente1_idx` ON `trocagame`.`cliente_has_badge` (`cliente_username` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `trocagame`.`plataforma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trocagame`.`plataforma` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `trocagame`.`plataforma` (
  `id` BIGINT UNSIGNED NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `jogo_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `jogo_id`),
  CONSTRAINT `fk_plataforma_jogo1`
    FOREIGN KEY (`jogo_id`)
    REFERENCES `trocagame`.`jogo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;
CREATE INDEX `fk_plataforma_jogo1_idx` ON `trocagame`.`plataforma` (`jogo_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `trocagame`.`proposta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trocagame`.`proposta` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `trocagame`.`proposta` (
  `id` DOUBLE NOT NULL,
  `dataHora` DATETIME NULL,
  `cliente_username` VARCHAR(20) NOT NULL,
  `midia_id` INT UNSIGNED NOT NULL,
  `midia_jogo_id` BIGINT UNSIGNED NOT NULL,
  `midia_cliente_username` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`, `cliente_username`),
  CONSTRAINT `fk_proposta_cliente1`
    FOREIGN KEY (`cliente_username`)
    REFERENCES `trocagame`.`cliente` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proposta_midia1`
    FOREIGN KEY (`midia_id` , `midia_jogo_id` , `midia_cliente_username`)
    REFERENCES `trocagame`.`midia` (`id` , `jogo_id` , `cliente_username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;
CREATE INDEX `fk_proposta_cliente1_idx` ON `trocagame`.`proposta` (`cliente_username` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_proposta_midia1_idx` ON `trocagame`.`proposta` (`midia_id` ASC, `midia_jogo_id` ASC, `midia_cliente_username` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
